name: lightning_runner
description: Implement your native HMR easily on your Dart project.
version: 1.0.0
# homepage: https://www.example.com
executables:
  lightning_runner: lightning_runner

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.15.0
  logging: ^1.0.0
  path: ^1.8.0
  stream_transform: ^2.0.0
  vm_service: ">=6.0.1 <10.0.0"
  watcher: ^1.0.0
